accordion-padding = 30
automatically-unhide-macos-hidden-apps = true
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = ["/bin/bash", "-c", "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"]
on-focus-changed = ["move-mouse window-lazy-center", "exec-and-forget sketchybar --trigger aerospace_focus_change"]
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = true

[gaps.inner]
horizontal = 5
vertical = 5

[gaps.outer]
bottom = 5
left = 5
right = 5
top = {{ if eq (env.Getenv "AEROSPACE_MODE") "laptop" }}15{{ else }}45{{ end }}

[key-mapping]
preset = "qwerty"

[workspace-to-monitor-force-assignment]
"S" = "Built-in Retina Display"
"V" = "DELL U3425WE"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-s = "workspace S"
alt-v = "workspace V"
alt-comma = "layout accordion horizontal vertical"
alt-period = "layout tiles horizontal vertical"
alt-f = "fullscreen"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-r = "mode resize"
ctrl-alt-right = "workspace next"
ctrl-alt-left = "workspace prev"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-s = "move-node-to-workspace S"
alt-shift-v = "move-node-to-workspace V"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-shift-semicolon = "mode service"
#alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-slash = "layout tiles horizontal vertical"
alt-tab = "workspace-back-and-forth"

# Function key app focus bindings (current workspace only)
f1 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Cursor'"
f2 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Comet'"
f3 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Slack'"
f4 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Linear'"
f5 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Notion'"
f6 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'ChatGPT'"
f7 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Obsidian'"
f8 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Superhuman'"
f9 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Notion Calendar'"
f10 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Todoist'"
f12 = "exec-and-forget /Users/gg/.local/bin/aerospace-focus-app 'Warp' new"

[mode.resize.binding]
b = ["balance-sizes", "mode main"]
equal = "resize smart +50"
esc = "mode main"
minus = "resize smart -50"

[mode.service.binding]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
down = "volume down"
esc = ["reload-config", "mode main"]
f = ["layout floating tiling", "mode main"]
r = ["flatten-workspace-tree", "mode main"]
shift-down = ["volume set 0", "mode main"]
up = "volume up"

## App-to-workspace rules
[[on-window-detected]]
    if.app-id = "com.tinyspeck.slackmacgap"
    run = ["move-node-to-workspace 1"]

[[on-window-detected]]
    if.app-id = "com.Linear"
    run = ["move-node-to-workspace 1"]

[[on-window-detected]]
    if.app-id = "com.spotify.client"
    run = ["move-node-to-workspace S"]

[[on-window-detected]]
    if.app-id = "com.granola.app"
    run = ["move-node-to-workspace V"]

[[on-window-detected]]
    if.app-id = "com.cron.electron"
    run = ["move-node-to-workspace V"]

[[on-window-detected]]
    if.app-id = "com.apple.finder"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "com.apple.Notes"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "notion.id"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "com.1password.1password"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "com.apple.Preview"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "dev.kdrag0n.MacVirt"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "com.elgato.StreamDeck"
    run = ["layout floating"]

[[on-window-detected]]
    if.app-id = "com.hegenberg.BetterTouchTool"
    run = ["layout floating"]

# Defaults: ensure tiling for windows on target workspaces at startup
[[on-window-detected]]
if.workspace = "V"
if.during-aerospace-startup = true
run = ["layout tiling"]

[[on-window-detected]]
if.workspace = "S"
if.during-aerospace-startup = true
run = ["layout tiling"]

[[on-window-detected]]
if.workspace = "1"
if.during-aerospace-startup = true
run = ["layout tiling"]

[[on-window-detected]]
if.workspace = "2"
if.during-aerospace-startup = true
run = ["layout tiling"]

[[on-window-detected]]
if.workspace = "3"
if.during-aerospace-startup = true
run = ["layout tiling"]

[[on-window-detected]]
if.workspace = "4"
if.during-aerospace-startup = true
run = ["layout tiling"]

