# column_width = 200
# line_endings = "Unix"
# indent_type = "Spaces"
# collapse_simple_statement = false

indent_type = "Spaces"
quote_style = "AutoPreferDouble"
call_parentheses = "None"
indent_width = 2

[sort_requires]
enabled = true
